// Code generated by "stringer -type=SortDirection -linecomment -output=direction_string.go"; DO NOT EDIT.

package smugmug

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DirectionNone-0]
	_ = x[DirectionAscending-1]
	_ = x[DirectionDescending-2]
}

const _SortDirection_name = "NoneAscendingDescending"

var _SortDirection_index = [...]uint8{0, 4, 13, 23}

func (i SortDirection) String() string {
	if i < 0 || i >= SortDirection(len(_SortDirection_index)-1) {
		return "SortDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortDirection_name[_SortDirection_index[i]:_SortDirection_index[i+1]]
}
