// Code generated by "stringer -type=SortMethod -linecomment -output=method_string.go"; DO NOT EDIT.

package smugmug

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MethodNone-0]
	_ = x[MethodRank-1]
	_ = x[MethodLastUpdated-2]
}

const _SortMethod_name = "NoneRankLastUpdated"

var _SortMethod_index = [...]uint8{0, 4, 8, 19}

func (i SortMethod) String() string {
	if i < 0 || i >= SortMethod(len(_SortMethod_index)-1) {
		return "SortMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SortMethod_name[_SortMethod_index[i]:_SortMethod_index[i+1]]
}
