# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  default:
    cmds:
      - task: demo

  demo:
    desc: Run the smugmug demo
    cmds:
      - go run cmd/demo/*.go {{.CLI_ARGS}}

  test:
    desc: Run tests
    cmds:
      - go test ./...
