# https://taskfile.dev

version: '3'

vars:
  CWD:
    sh: git rev-parse --show-toplevel
  DIST:
    "{{.CWD}}/.dist"

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run tests
    cmds:
      - mkdir -p {{.DIST}}
      - go test -count=1 -covermode count -coverprofile {{.DIST}}/coverage.txt github.com/bzimmer/smugmug github.com/bzimmer/smugmug/uploadable/filesystem

  cover:
    desc: Visualize test coverage
    deps: [test]
    cmds:
      - go tool cover -html={{.DIST}}/coverage.txt
